import Head from 'next/head'
import Navbar from "../components/navbar/Navbar"
import Slider from "../components/slider/Slider"
import Cnavbar from '../components/catogories/Cnavbar'
import Imp from "../components/images/Imp"
import Grid from '../components/images/imagecomponent'
import Card1 from '../components/card_1/Card_main_1'
import Footer from '../components/Footer/Footer'
import Image from 'next/image'
import Productscarousoul from '../components/cards_Slider/Productscarousoul'
const images: string[] = ["/images/adrianna-geo-1rBg5YSi00c-unsplash.jpg", "/images/europeana-5TK1F5VfdIk-unsplash.jpg", "/images/jene-stephaniuk--MCrF6hnojU-unsplash.jpg", "/images/adrianna-geo-1rBg5YSi00c-unsplash.jpg","/images/windows-L0xLAqyz4N4-unsplash.jpg"]
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <div className="mx-auto w-[80vw] grid gap-10">
        <main className=' mt-10 main_section mx-auto w-[80vw] flex justify-center gap-8 relative'>
          <div className='w-[50%]'>

          <Cnavbar />
          </div>
          <div className="slider w-[100%]">
            <Slider images={images}></Slider>
          </div>
        </main>
        <aside className='flex flex-col gap-10 '>
          <div className="images flex gap-6 justify-center">
            <Imp />
            <Imp />
            <Imp />
          </div>
          <aside className='flex bg-slate-100 justify-center '>
          <Card1/>
          </aside>
          <div className="productcarousol shadow-2xl">
             <Productscarousoul heading={"Heading"}/>
          </div>
          <div className="images flex gap-6 justify-center">
            <Imp />
            <Imp />
            <Imp />
          </div>
          <div className="productcarousol shadow-2xl">
             <Productscarousoul heading={"Heading"}/>
          </div>
        </aside>
      </div>
      <Footer />
    </>
  )
}
